# Generated by Django 4.1.7 on 2023-03-28 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_plan.direction')),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': '6. Guruhlar',
            },
        ),
    ]
