# Generated by Django 4.1.7 on 2023-03-22 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_visitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Super Visitor',
                'verbose_name_plural': '2. Super kuzatuvchilar',
            },
        ),
    ]
