# Generated by Django 4.1.7 on 2023-03-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_visitor', '0003_logins'),
    ]

    operations = [
        migrations.AddField(
            model_name='logins',
            name='role',
            field=models.CharField(choices=[('super_visitor', 'super_visitor'), ('dekan', 'dekan'), ('mudir', 'mudir'), ('education_officer', 'education_officer'), ('other', 'other')], default='other', max_length=20),
        ),
    ]
