# Generated by Django 4.1.7 on 2023-03-22 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('manager', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.facultymanager')),
            ],
            options={
                'verbose_name': 'Fakultet',
                'verbose_name_plural': '2. Fakultetlar',
            },
        ),
    ]
