# Generated by Django 4.1.7 on 2023-03-23 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafedra', '0002_cafedra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafedra',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafedra.cafedramanager'),
        ),
    ]
